### ISSUE TITLE
Allow spaces as `num` thousand separators

### ISSUE THREAD

**Issue by genericusername3** [ChHecker/unify#32]
Currently, separators for `num` are trimmed, meaning it is not possible to set e.g. `" "` or `sym.space.nobreak` or `sym.space.nobreak.narrow` as the thousands separator, which is inconvenient for formatting a number like e.g. `4446536` as 4&#x202F;446&#x202F;536

**Comment by ChHecker** [comment]
That's an interesting point. A quick intermediate fix would be using the `#h` command to specify a fixed space, this would however not automatically scale with the space width.
As a permanent solution, removing the trimming of the separator probably makes sense.

**Comment by ChHecker** [comment]
I don't actually think the `trim` is the problem, as it's only used for comparison, and removing it doesn't solve the problem. I think the problem is rather that whitespaces in the source code in math mode don't produce whitespaces in the document in Typst in general. Therefore, this wouldn't really make sense to be solved in this package, and you need to fall back to Typst spacing functions.

**Comment by ChHecker** [comment]
That's a good point. Added it to the README.
