### ISSUE TITLE
Degree after percent causes error

### ISSUE THREAD

**Issue by alex210-1** [ChHecker/unify#34]
both `$qty("0.393", "% / d K")$` and `$qty("0.393", "percent per degree kelvin")$`

Cause the error `unknown variable: percentdegree` in unify 0.6.0

**Comment by ChHecker** [comment]
This is actually intended behavior. The degree symbol by its own may only be used directly after a number. The temperature units, however, are allowed on their own. If you e.g. want to use "percent per degree Celsius", `#qty("0.393", "% / dC")` will work because instead of manually using `d C`, the unit `dC` is used as one.
In the case of Kelvin, this won't work for a very specific reason: Kelvin is not given in degrees, as it is an absolute scale. The physically proper way would thus be `#qty("0.393", "% / K")`.
